// Writes lib/server/invoice/fonts.generated.ts from the Fontsource packages.
//
//   node scripts/brand/generate_invoice_fonts.mjs
//
// Re-run after upgrading @fontsource/inter or @fontsource/bodoni-moda; the
// packages are devDependencies because nothing reads them at runtime.
//
// WHY A GENERATED MODULE AND NOT THE FILES. A route handler on Vercel runs from
// a function bundle that contains what the code IMPORTS. public/ is not in it,
// and neither is a node_modules file the tracer cannot see being required —
// so reading a font from disk works locally and fails in production. Base64 in
// an imported module is always there.
//
// WHY .woff AND NOT .woff2, WHICH IS SMALLER. fontkit — what pdfkit subsets
// fonts with — crashes on WOFF2's transformed glyph table as soon as it meets
// a composite glyph (an accented letter built from a base and a mark):
// "RangeError: Offset is outside the bounds of the DataView". Plain WOFF keeps
// the glyph table intact. Tested on every file below.
//
// WHY STATIC INSTANCES AND NOT THE SITE'S OWN FONTS. public/fonts holds
// variable fonts, which fontkit cannot subset reliably either.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'

const OUT = 'lib/server/invoice/fonts.generated.ts'

const FONTS = {
  // Body text, in the three subsets a customer's name can need.
  interLatin400: ['inter', 'inter-latin-400-normal.woff'],
  interLatinExt400: ['inter', 'inter-latin-ext-400-normal.woff'],
  interCyrillic400: ['inter', 'inter-cyrillic-400-normal.woff'],
  // Labels and totals.
  interLatin600: ['inter', 'inter-latin-600-normal.woff'],
  // The wordmark and headings, as on the site.
  bodoniLatin500: ['bodoni-moda', 'bodoni-moda-latin-500-normal.woff'],
}

let body = ''
let total = 0
for (const [name, [pkg, file]] of Object.entries(FONTS)) {
  const bytes = readFileSync(`node_modules/@fontsource/${pkg}/files/${file}`)
  total += bytes.length
  body += `/** ${file} (${(bytes.length / 1024).toFixed(0)} KB) */\nexport const ${name} = '${bytes.toString('base64')}'\n\n`
}

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(
  OUT,
  `// GENERATED by scripts/brand/generate_invoice_fonts.mjs — do not edit by hand.\n` +
    `// Static WOFF instances of Inter and Bodoni Moda, base64, for the PDF invoice.\n` +
    `// See the script for why they are embedded and why .woff rather than .woff2.\n` +
    `import 'server-only'\n\n` +
    body,
)
console.log(`wrote ${OUT} — ${Object.keys(FONTS).length} fonts, ${(total / 1024).toFixed(0)} KB before base64`)
