// GENERATED by scripts/brand/generate_brand_assets.py — do not edit by hand.
// Change the geometry there and re-run it; every icon is rewritten with it.

/** The LV monogram, centred in a 512x512 box. Didone contrast, for large sizes. */
export const MONOGRAM_PATH = 'M108 146L150 146L150 366L108 366ZM92 146L166 146L166 154L92 154ZM92 358L226 358L226 366L92 366ZM218 316L226 316L226 366L218 366ZM246 154L290 154L340 366L313.6 366ZM396 154L404 154L340 366L330.4 366ZM228 146L308 146L308 154L228 154ZM380 146L420 146L420 154L380 154Z'

/** Heavier strokes for small sizes, where a hairline would vanish. */
export const MONOGRAM_BOLD_PATH = 'M92 146L152 146L152 366L92 366ZM76 146L168 146L168 168L76 168ZM76 344L228 344L228 366L76 366ZM206 316L228 316L228 366L206 366ZM248 168L310 168L360 366L322.8 366ZM398 168L420 168L360 366L333.6 366ZM230 146L328 146L328 168L230 168ZM382 146L436 146L436 168L382 168Z'

/** A standalone SVG of the monogram: gold by default, optionally on a background. */
export function monogramSvg(opts: { fill?: string; background?: string } = {}): string {
  const fill = opts.fill ?? '#D4AF37'
  const ground = opts.background ? `<rect width="512" height="512" fill="${opts.background}"/>` : ''
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">${ground}<path fill="${fill}" d="${MONOGRAM_PATH}"/></svg>`
}
