"""Where the app talks to and where it keeps its files.

The server address is baked in at build time (`build.ps1 -ServerUrl https://api.myjarvis.com` writes
`_build.py`); JARVIS_URL overrides it for development.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

try:  # generated by desktop/build/build.ps1
    from app._build import SERVER_URL as _BUILD_URL  # type: ignore[import-not-found]
except ImportError:
    _BUILD_URL = "http://localhost"

SERVER_URL = (os.environ.get("JARVIS_URL") or _BUILD_URL).rstrip("/")
APP_NAME = "JARVIS"
KEYRING_SERVICE = "JARVIS"  # Windows Credential Manager → "JARVIS" generic credential


def data_dir() -> Path:
    base = os.environ.get("LOCALAPPDATA") or str(Path.home() / ".local" / "share")
    d = Path(base) / APP_NAME
    d.mkdir(parents=True, exist_ok=True)
    return d


def resource(name: str) -> Path:
    """A file shipped next to the code (inside the PyInstaller bundle when frozen)."""
    root = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent.parent))
    return root / "resources" / name
